
package Ventanas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class Usuarios extends javax.swing.JFrame {

    static Connection conn=null;
    static Statement s=null;
    static ResultSet rs=null;
    
    String paterno1="",materno1="",nombre1="",idperso="",sucursal="",ecatepec="ECATEPEC",coacalco="COACALCO";
    
    public Usuarios() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.jpg")).getImage());
        ((JPanel) getContentPane()).setOpaque(false);
        setLocationRelativeTo(null);
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            Character c = evt.getKeyChar();
            if(Character.isLetter(c)) {
                evt.setKeyChar(Character.toUpperCase(c));
            }
            }});
        contraseña1.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            Character c = evt.getKeyChar();
            if(Character.isLetter(c)) {
                    evt.setKeyChar(Character.toUpperCase(c));
            }
            }});
        
        contraseña2.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            Character c = evt.getKeyChar();
            if(Character.isLetter(c)) {
                    evt.setKeyChar(Character.toUpperCase(c));
            }
            }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contraseña1 = new javax.swing.JTextField();
        contraseña2 = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idpersonal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contraseña1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseña1KeyTyped(evt);
            }
        });

        contraseña2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseña2KeyTyped(evt);
            }
        });

        Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ID.png"))); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setText("ID Personal");

        idpersonal.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        idpersonal.setText("ID Personal");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setText("La Contraseña no debe exceder los 10 digitos");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel5.setText("Contraseña");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel6.setText("Confirme Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpersonal)
                            .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71)
                        .addComponent(contraseña1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Aceptar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(contraseña2))))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idpersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
    
        try{
                         conn=Conexion.Enlace(conn);
                         String MAX="SELECT NOMBRE,PATERNO,MATERNO,SUCURSAL FROM PERSONAL WHERE ID_PERSONAL='" + idpersonal.getText() +"'";
                         Statement st=conn.createStatement();
                         ResultSet rs=st.executeQuery(MAX);
                         if(rs.next()){
                             paterno1=rs.getString("PATERNO");
                             materno1=rs.getString("MATERNO");
                             nombre1=rs.getString("NOMBRE");
                             sucursal=rs.getString("SUCURSAL");
                          }
                                }catch(SQLException e){
                                    
                                }
        System.out.println(nombre1+ "" + sucursal);

if(sucursal.equals(coacalco)){
try{
conn=Conexion.Enlace(conn);   
conn.setAutoCommit(false);
conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
conn.commit();


 try{
                         
                         String MAX="SELECT ID_PERSONAL FROM PERSONAL@DBLINKCHAVA WHERE NOMBRE='" + nombre1 +"' AND PATERNO='" + paterno1 + "' AND MATERNO='" + materno1 + "'";
                         Statement st=conn.createStatement();
                         ResultSet rs=st.executeQuery(MAX);
                         if(rs.next()){
                             idperso=rs.getString("ID_PERSONAL");
                          }
                                }catch(SQLException e){
                                    
                                }
try {
            
            if(idpersonal.getText().trim().length()==0 || usuario.getText().trim().length()==0 || contraseña1.getText().trim().length()==0 || contraseña2.getText().trim().length()==0 ) {
                JOptionPane.showMessageDialog(null,"POR FAVOR, INGRESE LOS DATOS NECESARIOS");
            }else{
                    if(contraseña1.getText().equals(contraseña2.getText())){
                        String Variable= "1";

                        String sqlinsertar="INSERT INTO USUARIOS@DBLINKCHAVA values (?,?,?,?)";
                        PreparedStatement psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idperso );
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();
                        
                        sqlinsertar="INSERT INTO USUARIOS@DBLINKBETO values (?,?,?,?)";
                        psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idperso );
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();
                        
                        sqlinsertar="INSERT INTO USUARIOS@DBLINKHUGO values (?,?,?,?)";
                        psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idperso );
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();
                        
                        sqlinsertar="INSERT INTO USUARIOS values (?,?,?,?)";
                        psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idpersonal.getText());
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();

                     JOptionPane.showMessageDialog(null, "El Usuario "+usuario.getText()+" con ID "+idpersonal.getText()+" ha sido agregado con éxito");
                     dispose();



                    }else{
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden. Intentelo de nuevo");
                      }
            
            }
           } catch (SQLException ex) {
            
           }
                    
                    conn.commit();
                    conn.close();
                    
    } catch (SQLException ex) {
      ex.printStackTrace();
      } try {
           conn.rollback();
           System.out.println("Transaction failed. No records were written to the database.");
            }
             catch (SQLException se) {
             se.printStackTrace();
            }

}
else if(sucursal.equals(ecatepec)){
try{
conn=Conexion.Enlace(conn);   
conn.setAutoCommit(false);
conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
conn.commit();

try{
                         conn=Conexion.Enlace(conn);
                         String MAX="SELECT ID_PERSONAL FROM PERSONAL@DBLINKRICHI WHERE NOMBRE='" + nombre1 +"' AND PATERNO='" + paterno1 + "' AND MATERNO='" + materno1 + "'";
                         Statement st=conn.createStatement();
                         ResultSet rs=st.executeQuery(MAX);
                         if(rs.next()){
                             idperso=rs.getString("ID_PERSONAL");
                          }
                                }catch(SQLException e){
                                    
                                }

try {
            
            if(idpersonal.getText().trim().length()==0 || usuario.getText().trim().length()==0 || contraseña1.getText().trim().length()==0 || contraseña2.getText().trim().length()==0 ) {
                JOptionPane.showMessageDialog(null,"POR FAVOR, INGRESE LOS DATOS NECESARIOS");
            }else{
                    if(contraseña1.getText().equals(contraseña2.getText())){
                        String Variable= "1";

                        String sqlinsertar="INSERT INTO USUARIOS@DBLINKRICHI values (?,?,?,?)";
                        PreparedStatement psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idperso );
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();
                        
                        sqlinsertar="INSERT INTO USUARIOS@DBLINKMATA values (?,?,?,?)";
                        psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idperso );
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();
                        
                        sqlinsertar="INSERT INTO USUARIOS@DBLINKPROFE values (?,?,?,?)";
                        psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idperso );
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();

                        sqlinsertar="INSERT INTO USUARIOS values (?,?,?,?)";
                        psta=conn.prepareStatement(sqlinsertar);
                        psta.setString(1, idpersonal.getText());
                        psta.setString(2, usuario.getText());
                        psta.setString(3, contraseña1.getText());
                        psta.setString(4, Variable);                   
                        psta.execute();
                        
                     JOptionPane.showMessageDialog(null, "El Usuario "+usuario.getText()+" con ID "+idpersonal.getText()+" ha sido agregado con éxito");
                     dispose();
        
                    }else{
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden. Intentelo de nuevo");
                      }
            }
            
            
           } catch (SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
           }
                    
                    conn.commit();
                    conn.close();
                    
    } catch (SQLException ex) {
      ex.printStackTrace();
      } try {
           conn.rollback();
           System.out.println("Transaction failed. No records were written to the database.");
            }
             catch (SQLException se) {
             se.printStackTrace();
            }

    }


    }//GEN-LAST:event_AceptarActionPerformed

    private void contraseña1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseña1KeyTyped
        int limite=10;
        if(contraseña1.getText().length()>=limite){
            evt.consume();
        }
    }//GEN-LAST:event_contraseña1KeyTyped

    private void contraseña2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseña2KeyTyped
        int limite=10;
        if(contraseña2.getText().length()>=limite){
            evt.consume();
        }
    }//GEN-LAST:event_contraseña2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField contraseña1;
    private javax.swing.JTextField contraseña2;
    public static javax.swing.JLabel idpersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
